// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SvRus_3.Models;

namespace SvRus_3.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SvRus_3.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descriptin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EmployeePostedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Head")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeePostedId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SvRus_3.Models.Notice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descriptin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EmployeePostedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Head")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeePostedId");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("SvRus_3.Models.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descriptin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EmployeePostedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Head")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeePostedId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("SvRus_3.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RoleAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SvRus_3.Models.Item", b =>
                {
                    b.HasOne("SvRus_3.Models.User", "EmployeePosted")
                        .WithMany()
                        .HasForeignKey("EmployeePostedId");
                });

            modelBuilder.Entity("SvRus_3.Models.Notice", b =>
                {
                    b.HasOne("SvRus_3.Models.User", "EmployeePosted")
                        .WithMany()
                        .HasForeignKey("EmployeePostedId");
                });

            modelBuilder.Entity("SvRus_3.Models.Photo", b =>
                {
                    b.HasOne("SvRus_3.Models.User", "EmployeePosted")
                        .WithMany()
                        .HasForeignKey("EmployeePostedId");
                });
#pragma warning restore 612, 618
        }
    }
}
